name: Sync Repositories Daily

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 时间 00:00 执行
  workflow_dispatch:  # 允许手动触发

permissions:
  contents: write

jobs:
  sync-repos:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout own repository
      uses: actions/checkout@v4
      with:
        repository: ${{ github.repository }}
        GH_TOKEN: ${{ secrets.PAT }}
        fetch-depth: 0

    - name: Install GitHub CLI
      run: |
        sudo apt update && sudo apt install -y gh
        gh auth status || echo "GitHub CLI installed"
        
    - name: Authenticate GitHub CLI
      env:
        GH_TOKEN: ${{ secrets.PAT }}
      run: gh auth status
      
    - name: Sync repositories
      run: |
        
        # 读取 repo.conf 文件
        while IFS= read -r line; do
          [[ $line =~ ^\[(.*)\]$ ]] && section="${BASH_REMATCH[1]}" && continue
          [[ $line =~ ^repo\ =\ (.*)$ ]] && remote_repo="${BASH_REMATCH[1]}" && continue
          [[ $line =~ ^repo\ =\ (.*)$ ]] && own_repo="${BASH_REMATCH[1]}" && continue
          [[ $line =~ ^repo\ =\ (.*)$ ]] && branch="${BASH_REMATCH[1]}" && continue
          # 同步仓库
          echo "Syncing $remote_repo -> $own_repo on branch $branch"
          git clone "https://github.com/${remote_repo}" "${section}"

          # 进入子目录
          pushd ${section}

          # 1️⃣ 检查 own_repo 是否存在
          if ! gh repo view $GITHUB_ACTOR/$own_repo &>/dev/null; then
            echo "Repository $own_repo not found. Forking from $remote_repo..."
            
            # 2️⃣ 尝试 fork
            gh repo fork $remote_repo --clone=false --remote=true || {
              echo "Forking failed! Ensure the token has 'public_repo' or 'repo' permissions."
              exit 1
            }
          fi
          
          git remote add upstream https://github.com/$own_repo.git || git remote set-url upstream https://github.com/$own_repo.git
          git fetch upstream $branch
          git checkout $branch
          git merge --ff-only origin/$branch || echo "Merge conflict detected, skipping $own_repo"
          git push upstream $branch
          
          popd
        done < repo.conf
      env:
        GH_TOKEN: ${{ secrets.PAT }}
        
