name: Auto-Fork Repositories
on:
  workflow_dispatch: # 允许手动触发
  schedule:
    - cron: '0 0 * * *' # 每天自动检查一次

jobs:
  fork-repositories:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { remote: 'Flopcoin/Flopcoin', own: 'Flopcoin', branch: 'master' }
          - { remote: 'dogecoin/dogecoin', own: 'dogecoin', branch: 'master' }
    steps:
      - name: Check repository existence
        id: check-repo
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }} # 需要创建有 repo 权限的 PAT
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ matrix.config.own }}
        run: |
          response=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/$OWNER/$REPO")

          if [[ $(echo "$response" | jq -r .message) == "Not Found" ]]; then
            echo "exists=false" >> $GITHUB_OUTPUT
          else
            echo "exists=true" >> $GITHUB_OUTPUT
          fi

      - name: Fork repository
        if: ${{ steps.check-repo.outputs.exists == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          REMOTE_REPO: ${{ matrix.config.remote }}
        run: |
          curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Content-Length: 0" \
            "https://api.github.com/repos/$REMOTE_REPO/forks"
          
          echo "Successfully forked $REMOTE_REPO"
