name: Sync Repositories Daily

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 时间 00:00 执行
  workflow_dispatch:  # 允许手动触发

permissions:
  contents: write

jobs:
  sync-repos:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout own repository
      uses: actions/checkout@v4
      with:
        repository: ${{ github.repository }}
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
        
    - name: Sync repositories
      run: |
        # 读取 repo.conf 文件
        while IFS= read -r line; do
          [[ $line =~ ^\[(.*)\]$ ]] && section="${BASH_REMATCH[1]}" && continue
          [[ $line =~ ^repo\ =\ (.*)$ ]] && remote_repo="${BASH_REMATCH[1]}" && continue
          [[ $line =~ ^repo\ =\ (.*)$ ]] && own_repo="${BASH_REMATCH[1]}" && continue
          [[ $line =~ ^repo\ =\ (.*)$ ]] && branch="${BASH_REMATCH[1]}" && continue
          # 同步仓库
          echo "Syncing $remote_repo -> $own_repo on branch $branch"
          git remote add upstream https://github.com/$remote_repo.git || git remote set-url upstream https://github.com/$remote_repo.git
          git fetch upstream $branch
          git checkout $branch
          git merge --ff-only upstream/$branch || echo "Merge conflict detected, skipping $own_repo"
          git push origin $branch
        done < repo.conf
